stages:
  - build
  - test
  - deploy

image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - npm ci || npm install

build:
  stage: build
  script:
    - node bin/automata.js run --stage build

test:
  stage: test
  script:
    - node bin/automata.js run --stage test

deploy:
  stage: deploy
  script:
    - node bin/automata.js run --stage deploy
  only:
    - main


